# Рабочая тетрадь №2

## Теоретический материал

### Библиотека NumPy

NumPy (<b>Num</b>erical<b>Py</b>thon) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.
<p>Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
<br>&nbsp;&nbsp;pip install numpy
<p>Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
<br>&nbsp;&nbsp;import numpy as np
<p>Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
<p>Наиболее важные атрибуты объектов ndarray:
<br><b>ndarray.ndim</b> - число измерений (чаще их называют "оси") массива.
<br><b>ndarray.shape</b> - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
<br><b>ndarray.size</b> - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
<br><b>ndarray.dtype</b> - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
<br><b>ndarray.itemsize</b> - размер каждого элемента массива в байтах.
<br><b>ndarray.data</b> - буфер, содержащий фактические элементы массива.
<p>Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.
<p>Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html

## Пример 1.2.1

Задание:
<br>Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np
x = np.array([[2, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 2  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


## Пример 1.2.2

Задание:
<br>Выполнить следующее:

1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [2]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


## Пример 1.2.3

Задание:
<br>Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [3]:
import numpy as np

Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print("Минимум: ", round(Zmin, 3),"\nМаксимум: ", round(Zmax, 3), "\nСреднее значение: ", round(Zmean, 3))

Минимум:  0.015 
Максимум:  0.997 
Среднее значение:  0.471


## Пример 1.2.4

Задание:
<br>Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [2]:
import numpy as np

A = np.arange(25).reshape(5,5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Пример 1.2.5

Задание:
<br>Выяснить результат следующих выражений:
<br>0 * np.nan
<br>np.nan == np.nan
<br>np.inf > np.nan
<br>np.nan - np.nan
<br>0.3 == 3 * 0.1

In [3]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 2 * 0.1)

nan
False
False
nan
False


## Пример 1.2.6

Задание:
<br>Отсортировать массив.

In [4]:
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]



## Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np

# Создаем матрицу 8x8 с нулями
matrix = np.zeros((8, 8), dtype = int)

# Заполняем её единицами с шахматным порядком
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Задание 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [2]:
import numpy as np

matrix = np.zeros((5, 5)) + np.arange(5)
print("Матрица 5x5:\n", matrix)

Матрица 5x5:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Задание 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [111]:
import numpy as np

arr = np.random.rand(3, 3, 3)
print("Массив 3x3x3 со случайными значениями:\n", arr.round(3))

Массив 3x3x3 со случайными значениями:
 [[[0.082 0.96  0.233]
  [0.926 0.005 0.39 ]
  [0.316 0.554 0.543]]

 [[0.064 0.342 0.38 ]
  [0.799 0.858 0.595]
  [0.613 0.645 0.934]]

 [[0.062 0.18  0.867]
  [0.501 0.622 0.753]
  [0.031 0.832 0.071]]]


## Задание 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [13]:
import numpy as np

# Создание матрицы из единиц
matrix = np.ones((5, 5))

# Замена неграничных элементов на нули
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Задание 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [12]:
import numpy as np

# Создаем массив из 10 случайных чисел
arr = np.random.randint(0, 100, size=10)
 
# Сортируем по убыванию
arr_sorted = np.sort(arr)[::-1]

print(arr_sorted)

[96 92 86 80 63 56 56 53 38 10]


## Задание 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [6]:
import numpy as np

# Создаем матрицу 3x4, заполненную нулями
matrix = np.zeros((3, 4)) 

print("Форма:", matrix.shape) # Форма
print("Количество элементов:", matrix.size)  # Количество элементов
print("Размерность:", matrix.ndim)  # Размерность

Форма: (3, 4)
Количество элементов: 12
Размерность: 2


## Теоретический материал

### Библиотека Pandas

Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких источников.
<p><i>Библиотека pandas</i> – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то <i>pandas</i> – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для  ранения данных и работе с ними.
<p><i>Библиотека pandas</i> присутствует в стандартной поставке Anaconda. Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:
<br>&nbsp;&nbsp;pip install pandas
<br>Для импорта библиотеки используйте команду:
<br>&nbsp;&nbsp;import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.
<p><b>Series</b> – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
<p><b>DataFrame</b> – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

## Пример 2.2.1

Задание:
<br>Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [10]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


## Пример 2.2.2

Задание:
<br>Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [9]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


## Пример 2.2.3

Задание:
<br>Создайте новый фрейм данных.

In [7]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Имя'] = ['Иван', 'Мария', 'Кристина', 'Вадим', 'Никита']
dataframe['Возраст'] = [19, 20, 23, 19, 19]
dataframe['Средний балл'] = [4.9, 4.8, 4.1, 5.0, 2.8]
dataframe

Имя  Возраст  Средний балл
0      Иван       19           4.9
1     Мария       20           4.8
2  Кристина       23           4.1
3     Вадим       19           5.0
4    Никита       19           2.8

## Пример 2.2.4

Задание:
<br>Загрузите фрейм данных по ссылке:
<br>https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [9]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## Пример 2.2.5

Задание:
<br>Пронализировать характеристики фрейма данных.

In [10]:
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [11]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [12]:
dataframe.shape

(1313, 6)

In [13]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## Пример 2.2.6

Задание:
<br>Выберите индивидуальные данные или срезы фрейма данных.

In [14]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

## Пример 2.2.7

Задание:
<br>Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [15]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## Задание 2.3.1

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [84]:
import pandas as pd
import numpy as np

# Создание двух точек
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Находим евклидово расстояние между двумя Series
d = np.sqrt(np.sum((a - b) ** 2))

print("Евклидово пространство:", round(d, 3))

Евклидово пространство: 5.196


## Задание 2.3.2

Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных.

In [21]:
import pandas as pd

# Указываем URL-адрес файла, который хотим загрузить
url = 'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'

# Загружаем данные в объект dataframe
dataframe = pd.read_csv(url)

# Выводим первые 5 строк таблицы
dataframe.head(10)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0
7              3.2  54445.0
8              3.2  64445.0
9              3.7  57189.0

## Задание 2.3.3

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [26]:
import pandas as pd

# Указываем URL-адрес файла, который хотим загрузить
url = 'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'

# Загружаем данные в объект dataframe
dataframe = pd.read_csv(url)

# Выводим первые 5 строк таблицы
dataframe.head(5)

# Выводит последние 3 строки
dataframe.tail(3)

# Возвращает количество строк и столбцов
dataframe.shape

# Выбирает каждую 4-ую строку, начиная с индекса 1
dataframe.iloc[1::4]

YearsExperience    Salary
1               1.3   46205.0
5               2.9   56642.0
9               3.7   57189.0
13              4.1   57081.0
17              5.3   83088.0
21              7.1   98273.0
25              9.0  105582.0
29             10.5  121872.0

In [25]:
# Возвращает статистическую информацию для числовых столбцов
dataframe.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [29]:
# Выборка из датафрейма, где значение столбца 'salary' больше или равно 500,
# и вывод первых двух строк выборки.
dataframe[dataframe['Salary'] >= 50000].head(2)

YearsExperience   Salary
5              2.9  56642.0
6              3.0  60150.0

## Теоретический материал

### Работа с числовыми данными

Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, $529 392 продаж).
<p><b><i>Нормализация данных</i></b> — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
<p>Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.

На практике наиболее распространены следующие методы нормализации признаков:
- <b><i>Минимакс</i></b> – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения соответствуют 0 и 1 соответственно;
- <b><i>Z-масштабирование</i></b> данных на основе среднего значения и стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.

Нормализация по методу <b>минмакс</b>:
$$
  X_{norm} = \frac{X-X_{min}}{X_{max} - X_{min}}
$$
<br><b>Z-масштабирование</b>:
$$
  z = \frac{x - μ}{σ}
$$
<p>При масштабировании данных мы будем использовать одну из популярных библиотек машинного обучения <i>Scikit-learn</i>. Библиотека содержит пакет sklearn.preprocessing, который предоставляет широкие возможности для нормализации данных. Следует отметить, что в целом алгоритмы обучения выигрывают от стандартизации набора данных.

## Пример 3.2.1

Задание:
<br>Прошкалируйте числовой признак в диапазон между двумя значениями.

In [97]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## Пример 3.2.2

Задание:
<br>Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [108]:
import numpy as np
from sklearn import preprocessing

x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x).round(3)
# Показать признак
standardized

array([[-0.761],
       [-0.542],
       [-0.35 ],
       [-0.323],
       [ 1.975]])

In [72]:
print("Среднее:", round(standardized.mean(), 3))
print("Стандартное отклонение:", standardized.std())

Среднее: 0.0
Стандартное отклонение: 1.0


## Пример 3.2.3

Задание:
<br>Дан фрейм данных
<br>dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'B':[103.02,107.26,110.35,114.23,114.68],
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'C':['big','small','big','small','small']})
<br>Необходимо масштабировать его числовые столбцы.

In [107]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})

dfTest[['A', '8']] = scaler.fit_transform(dfTest[['A', 'B']]).round(3)
dfTest

A       B      C      8
0  0.000  103.02    big  0.000
1  0.926  107.26  small  0.364
2  0.935  110.35    big  0.629
3  1.000  114.23  small  0.961
4  0.938  114.68  small  1.000

## Задание 3.3.2

Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [110]:
import pandas as pd
from sklearn import preprocessing

# Указываем URL-адрес файла, который хотим загрузить
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

# Загружаем данные в объект dataframe
dataframe = pd.read_csv(url)
# print(dataframe)

# Создание шкалировщиков
minmax_scaler = preprocessing.MinMaxScaler()
z_scaler = preprocessing.StandardScaler()

# Прошкалирование
dataframe[['sepal_length_cm']] = minmax_scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = z_scaler.fit_transform(dataframe[['sepal_width_cm']])

# Вывод после применения методов нормализации
dataframe.round(3)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0              0.222           1.032              1.4             0.2   
1              0.167          -0.125              1.4             0.2   
2              0.111           0.338              1.3             0.2   
3              0.083           0.106              1.5             0.2   
4              0.194           1.263              1.4             0.2   
..               ...             ...              ...             ...   
145            0.667          -0.125              5.2             2.3   
146            0.556          -1.282              5.0             1.9   
147            0.611          -0.125              5.2             2.0   
148            0.528           0.801              5.4             2.3   
149            0.444          -0.125              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]